name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/docling_test.yml'

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  docling_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/docling_test.yml